{"name": "测试用例标题2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <pytest_test.testcase.test_class.Test_Fixture object at 0x1046b8898>\n\n    @allure.title(\"测试用例标题2\")\n    def case_b(self):\n        print(\"----test_b----\")\n>       assert 0\nE       assert 0\n\ntestcase/test_class.py:15: AssertionError"}, "start": 1574306773636, "stop": 1574306773636, "uuid": "aaf8f012-fcb8-4027-a832-291aea793912", "historyId": "50059e70e14d90a6dbcdf0573b43a65e", "fullName": "testcase.test_class.Test_Fixture#case_b", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "Test_Fixture"}, {"name": "host", "value": "wuyanhongdeMacBook-Pro.local"}, {"name": "thread", "value": "1139-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_class"}]}