{"name": "case_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <pytest_test.testcase.test_class.Test_Fixture object at 0x1086fda90>\n\n    def case_b(self):\n        print(\"----test_b----\")\n>       assert 0\nE       assert 0\n\ntestcase/test_class.py:14: AssertionError"}, "start": 1574306590490, "stop": 1574306590490, "uuid": "7854ca4b-d87b-439d-acc7-b4107c69532f", "historyId": "50059e70e14d90a6dbcdf0573b43a65e", "fullName": "testcase.test_class.Test_Fixture#case_b", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "Test_Fixture"}, {"name": "host", "value": "wuyanhongdeMacBook-Pro.local"}, {"name": "thread", "value": "1086-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_class"}]}