{"name": "测试用例标题2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <pytest_test.testcase.test_class.Test_Fixture object at 0x1109463c8>\n\n    @allure.title(\"测试用例标题2\")\n    @allure.description(\"测试用例2的描述\")\n    def case_b(self):\n        print(\"----test_b----\")\n        self.step_3()\n>       assert 0\nE       assert 0\n\ntestcase/test_class.py:35: AssertionError"}, "description": "测试用例2的描述", "steps": [{"name": "步骤3", "status": "passed", "start": 1574307403572, "stop": 1574307403572}], "start": 1574307403572, "stop": 1574307403573, "uuid": "87d0744a-a54c-40f1-b6ee-3bea59d7f82a", "historyId": "50059e70e14d90a6dbcdf0573b43a65e", "fullName": "testcase.test_class.Test_Fixture#case_b", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_class"}, {"name": "subSuite", "value": "Test_Fixture"}, {"name": "host", "value": "wuyanhongdeMacBook-Pro.local"}, {"name": "thread", "value": "1312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_class"}]}